# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faktureramera.ui'
#
# Created: Sat Apr 12 19:19:00 2014
#      by: PyQt5 UI code generator 5.0.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.customerGroup = QtWidgets.QGroupBox(self.tab)
        self.customerGroup.setMinimumSize(QtCore.QSize(200, 200))
        self.customerGroup.setMaximumSize(QtCore.QSize(16777215, 200))
        self.customerGroup.setObjectName("customerGroup")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.customerGroup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.customerGroup)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.customerGroup)
        self.comboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.newCustomerButton = QtWidgets.QPushButton(self.customerGroup)
        self.newCustomerButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.newCustomerButton.setObjectName("newCustomerButton")
        self.verticalLayout_4.addWidget(self.newCustomerButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.newCustomerLayout = QtWidgets.QVBoxLayout()
        self.newCustomerLayout.setObjectName("newCustomerLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.newCustomerLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.newCustomerLayout)
        self.verticalLayout_2.addWidget(self.customerGroup)
        self.jobsGroup = QtWidgets.QGroupBox(self.tab)
        self.jobsGroup.setObjectName("jobsGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.jobsGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jobsLayout = QtWidgets.QVBoxLayout()
        self.jobsLayout.setObjectName("jobsLayout")
        self.horizontalLayout_3.addLayout(self.jobsLayout)
        self.verticalLayout_2.addWidget(self.jobsGroup)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(640, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.saveGenerateButton = QtWidgets.QPushButton(self.groupBox_3)
        self.saveGenerateButton.setObjectName("saveGenerateButton")
        self.horizontalLayout_2.addWidget(self.saveGenerateButton)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.generateButton = QtWidgets.QPushButton(self.groupBox)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout.addWidget(self.generateButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Faktureramera"))
        self.customerGroup.setTitle(_translate("MainWindow", "Kund"))
        self.label.setText(_translate("MainWindow", "Kund:"))
        self.newCustomerButton.setText(_translate("MainWindow", "Ny"))
        self.jobsGroup.setTitle(_translate("MainWindow", "Jobb"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.saveGenerateButton.setText(_translate("MainWindow", "Generera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Fakturera"))
        self.generateButton.setText(_translate("MainWindow", "Generera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Historik"))

